name: Build and Push Docker Image from Nix

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checking disk space
        run: |
          df -h
        
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-25.05

      - name: Aggressive cleanup
        run: |
          # Remove Java (JDKs)
          sudo rm -rf /usr/lib/jvm

          # Remove .NET SDKs
          sudo rm -rf /usr/share/dotnet

          # Remove Swift toolchain
          sudo rm -rf /usr/share/swift

          # Remove Haskell (GHC)
          sudo rm -rf /usr/local/.ghcup

          # Remove Julia
          sudo rm -rf /usr/local/julia*

          # Remove Android SDKs
          sudo rm -rf /usr/local/lib/android

          # Remove Chromium (optional if not using for browser tests)
          sudo rm -rf /usr/local/share/chromium

          # Remove Microsoft/Edge and Google Chrome builds
          sudo rm -rf /opt/microsoft /opt/google

          # Remove Azure CLI
          sudo rm -rf /opt/az

          # Remove PowerShell
          sudo rm -rf /usr/local/share/powershell

          # Remove CodeQL and other toolcaches
          sudo rm -rf /opt/hostedtoolcache

          docker system prune -af || true
          docker builder prune -af || true
          df -h

      - name: Build Docker image with Nix
        working-directory: ./builder/
        run: nix build

      - name: Optimize
        run: nix-store --optimize
        
      - name: Cleanup phase
        run: nix-collect-garbage -d
        
      - name: Load Docker image
        working-directory: ./builder/
        run: docker load < result
      
      - name: Run to install home-manager
        run: |
          docker run --name nix-pentest nix-pentest-ctr /bin/bash /entrypoint.sh setup_channels

      - name: Commit the image
        run: |
          docker commit nix-pentest nix-pentest-ctr
        
      - name: Tag image for GitHub Container Registry
        run: |
          IMAGE_NAME=ghcr.io/vaelio/nix-pentest-ctr
          docker tag nix-pentest-ctr:latest $IMAGE_NAME:latest

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push to GitHub Container Registry
        run: |
          IMAGE_NAME=ghcr.io/vaelio/nix-pentest-ctr
          docker push $IMAGE_NAME:latest

